baseURL = 'http://noobfish.com/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
theme = 'coder'
title = 'Noobfish Studio - Build a New World'

[markup.highlight]
    style = 'github-light'

[params]
    author = 'NOOBFISH'
    info = ['Full Stack DevOps', 'Magician']
    since = '2023'
    avatarURL = 'http://www.wetools.com/imgplaceholder/512x512'
    colorScheme = 'light'
    hideColorSchemeToggle = 'true'

# Social links
[[params.social]]
    name = 'Github'
    icon = 'fa fa-github fa-2x'
    weight = 1
    url = 'https://github.com/Noobfish-Studio'

# Chinese Ver
[languages.zh-cn]
languageName = '中文'

[languages.zh-cn.params]
    info = ['全栈工程师', '魔术师']

[[languages.zh-cn.menu.main]]
    name = '新闻'
    weight = 1
    url = 'news/'

[[languages.zh-cn.menu.main]]
    name = '产品'
    weight = 2
    url = 'prod/'

[[languages.zh-cn.menu.main]]
    name = '关于'
    weight = 3
    url = 'about/'

# English Ver
[languages.en]
languageName = 'EN'

[languages.en.params]
    info = ['Full Stack DevOps', 'Magician']

[[languages.en.menu.main]]
    name = 'NEWS'
    weight = 1
    url = 'news/'

[[languages.en.menu.main]]
    name = 'PRODUCTS'
    weight = 2
    url = 'prod/'

[[languages.en.menu.main]]
    name = 'ABOUT'
    weight = 3
    url = 'about/'
