baseURL = 'http://noobfish.com/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
disableKinds = ["taxonomy", "term"]
theme = 'coder'

[taxonomies]
    category = "categories"
    tag = "tags"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

    [markup.highlight]
        style = 'github-light'

[params]
    author = 'NOOBFISH'
    info = ['This Changes Everything.', 'Again.']
    since = '2023'
    avatarURL = '/img/avatar.png'
    colorScheme = 'light'
    hideColorSchemeToggle = 'true'
    customSCSS = ['scss/custom.scss']

# Social links
[[params.social]]
    name = 'Github'
    icon = 'fa fa-github fa-2x'
    weight = 1
    url = 'https://github.com/Noobfish-Studio'

# Chinese Ver
[languages.zh-cn]
languageName = '中文'
title = 'NOOBFISH STUDIO - 又一次，改变世界'

[languages.zh-cn.params]
    info = '又一次，<br>改变世界。'
    dateFormat = '2006年 1月 2日'

[[languages.zh-cn.menu.main]]
    name = '新闻'
    weight = 1
    url = 'news/'

[[languages.zh-cn.menu.main]]
    name = '产品'
    weight = 2
    url = 'prod/'

[[languages.zh-cn.menu.main]]
    name = '关于'
    weight = 3
    url = 'about/'

# English Ver
[languages.en]
languageName = 'EN'
title = 'NOOBFISH STUDIO - This Changes Everything. Again.'

[languages.en.params]
    info = 'This Changes Everything.<br>Again.'
    dateFormat = 'January 2, 2006'

[[languages.en.menu.main]]
    name = 'NEWS'
    weight = 1
    url = 'news/'

[[languages.en.menu.main]]
    name = 'PRODUCTS'
    weight = 2
    url = 'prod/'

[[languages.en.menu.main]]
    name = 'ABOUT'
    weight = 3
    url = 'about/'
