baseURL = 'http://noobfish.com/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
theme = 'coder'
title = 'Noobfish Studio'

disqusShortname = 'yourdiscussshortname'

[markup.highlight]
    style = 'github-dark'

[params]
    author = 'Noobfish'
    info = ['Full Stack DevOps', 'Magician']
    since = '2023'
    avatarURL = '/img/avatar.jpg'

# Social links
[[params.social]]
    name = 'Github'
    icon = 'fa fa-github fa-2x'
    weight = 1
    url = 'https://github.com/Noobfish-Studio'

# Chinese Ver
[languages.zh-cn]
languageName = '中文'

[[languages.zh-cn.menu.main]]
    name = '首页'
    weight = 1
    url = ''

[[languages.zh-cn.menu.main]]
    name = '产品'
    weight = 2
    url = ''

[[languages.zh-cn.menu.main]]
    name = '关于'
    weight = 3
    url = ''

# English Ver
[languages.en]
languageName = 'EN'

[[languages.en.menu.main]]
    name = 'HOME'
    weight = 1
    url = ''

[[languages.en.menu.main]]
    name = 'PRODUCT'
    weight = 2
    url = ''

[[languages.en.menu.main]]
    name = 'ABOUT'
    weight = 3
    url = ''
